name: Docker

on:
  schedule:
    - cron: '30 1 * * 1' # run every Monday at 01:30
  workflow_dispatch:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

# Make sure there is no pipeline running uselessly.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set_date:
    runs-on: ubuntu-latest
    outputs:
      date_today: ${{ steps.date_step.outputs.today }}
    steps:
      - id: date_step
        run: echo "today=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

  publish_release:
    if: github.event.pull_request.merged == true
    needs: set_date
    uses: famedly/github-workflows/.github/workflows/docker.yml@49401388492ed7fe3eeb13fbefacf68168e9bc64
    with:
      push: true
      image_name: rust-container
      tags: |
        type=raw,value=nightly
        type=raw,value=nightly-${{needs.set_date.outputs.date_today}}
      build_args: |
        NIGHTLY_VERSION_DATE=${{needs.set_date.outputs.date_today}}
      registry: docker-oss.nexus.famedly.de
      registry_user: ${{ vars.NEXUS_REGISTRY_USER }}
    secrets: inherit

  publish_dev:
    if: github.event.pull_request.merged != true
    needs: set_date
    uses: famedly/github-workflows/.github/workflows/docker.yml@49401388492ed7fe3eeb13fbefacf68168e9bc64
    with:
      push: true
      image_name: rust-container
      tags: |
        type=raw,value=dev-${{ github.ref_name }}
      build_args: |
        NIGHTLY_VERSION_DATE=${{needs.set_date.outputs.date_today}}
      registry: docker-nightly.nexus.famedly.de
      registry_user: ${{ vars.NEXUS_REGISTRY_USER }}
    secrets: inherit
